name: Nightly workflow

on:
  workflow_dispatch:
  schedule:
    - cron:  '38 3 * * *'

permissions:
  contents: write

jobs:
  filter-update-tags:
    name: Get Tags and filter Outputs
    runs-on: ubuntu-latest
    outputs:
      versions: ${{steps.getdata.outputs.versions }}
    steps:
      - uses: actions/checkout@v4
      - name: Commit report
        run: |
          git config --global user.name 'Your Name'
          git config --global user.email 'your-username@users.noreply.github.com'
          git commit --allow-empty -m "Empty-Commit"
          git push
